packages:
  - apps/*
  - packages/*

catalog:
  "@types/better-sqlite3": 7.6.13
  "@types/node": 25.2.0
  "@vitest/browser-playwright": 4.0.18
  better-sqlite3: 12.6.2
  drizzle-orm: 0.45.1
  playwright: 1.58.1
  typescript: 5.9.3
  vitest: 4.0.18

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - lefthook
